// scripts/tagMap.js
// 
// Tag consolidation mappings for the Accountability Archive
// 
// This file defines how tags are consolidated during the rewrite process.
// Each key represents an original tag, and its value is the consolidated tag
// it should be mapped to. A value of `null` means the tag is retired entirely.
//
// For historical context and rationale behind consolidation decisions,
// see CONSOLIDATION_LOG.md in this directory.
//
// Usage: node scripts/rewriteTags.js
//

module.exports = {
  // Original mappings + preserved historical tags
  "Account Terminations": "Banking Relationships",
  "$TRUMP Coin": "Crypto",
  "Abuse of Power": "Oversight Interference",
  "Academic Freedom": "Academic Freedom",
  "Affinity Partners": "Trump Organization",
  "AI Surveillance": "AI Surveillance",
  "Alien Enemies Act": "Deportations",
  "Alternative Finance": "Financial Markets",
  "AmeriCorps": "Federal Agencies",
  "Apple": "Tech Platforms",
  "Asylum seekers": "Immigration Actions",
  "Aon": "Financial Markets",
  "Asset Seizures": "Oversight Interference",
  "Bank of America": "Banking Relationships",
  "Banking Relationships": "Financial Markets",
  "Bitcoin": "Crypto",
  "Blockchain": "Crypto",
  "Bond Market": "Financial Markets",
  "Brokerage Termination": "Banking Relationships",
  "Business owners": "Trump Organization",
  "Business Relationships": "Trump Organization",
  "Cabinet Reshuffling": "Trump Administration",
  "Campaign Event": "Campaign Finance",
  "Campaign Finance Violations": "Campaign Finance",
  "Campaign Fundraising": "Campaign Finance",
  "Capitol Riot": "Capitol Riot Fallout",
  "Capitol Riot Fallout": "Capitol Riot Fallout",
  "Censorship": "Press Freedom",
  "Changpeng Zhao": "Crypto",
  "China": "Foreign Influence",
  "Children detained": "Family separation",
  "CIC Ventures LLC": "Trump Organization",
  "CISA": "Cybersecurity",
  "Citizens detained": "Immigration Actions",
  "Climate Policy": "Regulatory Rollback",
  "Community response": "Press Freedom",
  "Conflict of Interest": "Conflicts of Interest",
  "Conflicts of Interest": "Conflicts of Interest",
  "Contracts Termination": "Business Relationships",
  "Corporate Accountability": "Oversight Interference",
  "Corporate Enforcement": "Ethics",
  "Criminal Justice": "Oversight Interference",
  "Crypto": "Crypto",
  "Crypto Ball": "Crypto",
  "Crypto Regulation": "Crypto",
  "Cruel and unusual punishment": "Rights Violations",
  "Cushman & Wakefield": "Business Relationships",
  "Cybersecurity": "Data Privacy",
  "Data Breach": "Data Privacy",
  "Data Privacy": "Data Privacy",
  "Debanking": "Banking Relationships",
  "Defense Department": "Federal Agencies",
  "Department of Defense": "Federal Agencies",
  "Department of Government Efficiency": "DOGE",
  "Department of Homeland Security": "Federal Agencies",
  "Department of Justice": "Federal Agencies",
  "Deplatforming": "Tech Platforms",
  "Deportations": "Deportations",
  "Detentions": "Citizens detained",
  "Digital Asset Policy": "Crypto",
  "Digital Assets": "Crypto",
  "DOGE": "DOGE",
  "Dollar Dominance": "Financial Markets",
  "Donald Trump": "Donald Trump",
  "Donor Access": "Pay-to-Play",
  "Donor Enrichment": "Conflicts of Interest",
  "Due Process Violations": "Rights Violations",
  "Early administration": "Trump Administration",
  "Election Interference": "Vote Buying",
  "El Salvador": "Deportations",
  "Elon Musk": "Elon Musk",
  "Emoluments": "Legal Challenges",
  "Emoluments Clause": "Emoluments",
  "Environmental Violations": "Regulatory Rollback",
  "Eric Trump": "Trump Organization",
  "Ethics": "Ethics",
  "Executive Order": "Legal Challenges",
  "Excessive force": "Rights Violations",
  "Facebook": "Tech Platforms",
  "Family Enrichment": "Conflicts of Interest",
  "Family Separation": "Immigration Actions",
  "FAA": "Federal Agencies",
  "Facial Recognition": "AI Surveillance",
  "Fake News": "Press Freedom",
  "Federal Agencies": "Federal Agencies",
  "Federal Budget": "Federal Agencies",
  "Federal Bureau of Prisons": "Department of Justice",
  "Federal Employees": "Federal Employees",
  "Federal Oversight": "Oversight Interference",
  "Federal Workforce": "Federal Employees",
  "Fidelity Investments": "Financial Markets",
  "Finance": "Financial Markets",
  "Financial Challenges": "Financial Markets",
  "Financial Disclosures": "Legal Challenges",
  "Financial Institutions": "Financial Markets",
  "Financial Markets": "Financial Markets",
  "Fintech": "Financial Markets",
  "FOIA": "Legal Challenges",
  "Foreign Aid": "Foreign Influence",
  "Foreign Business": "Foreign Influence",
  "Foreign Influence": "Foreign Influence",
  "Foreign Policy": "Foreign Influence",
  "Free Speech": "Free Speech",
  "Free speech": "Free Speech",
  "Fundraising": "Campaign Finance",
  "GENIUS Act": "Legal Challenges",
  "Ghislaine Maxwell": "Jeffrey Epstein",
  "Global Economy": "Financial Markets",
  "Goldman Sachs": "Banking Relationships",
  "Government Accountability": "Oversight Interference",
  "Government Administration": "Oversight Interference",
  "Government Communications": "Data Privacy",
  "Government Oversight": "Oversight Interference",
  "Government Restructuring": "DOGE",
  "Greenland": "Foreign Influence",
  "Harvard University": "Academic Freedom",
  "Healthcare": "Regulatory Rollback",
  "Healthcare impacts": "Regulatory Rollback",
  "ICE": "Federal Agencies",
  "Immigration": "Immigration Actions",
  "Immigration Actions": "Immigration Actions",
  "Immigration Policy": "Immigration Actions",
  "Impeachment": "Legal Challenges",
  "Influence Peddling": "Campaign Finance",
  "Inspectors General": "Oversight Interference",
  "Insurance": "Financial Markets",
  "Intelligence Community": "National Security",
  "International academics": "Academic Freedom",
  "International students": "Immigration Actions",
  "Investor Protection": "Financial Markets",
  "IRS": "Federal Agencies",
  "January 6": "Capitol Riot Fallout",
  "Jared Kushner": "Trump Organization",
  "Judicial Pushback": "Legal Challenges",
  "Kamala Harris": "Trump Administration",
  "Kristi Noem": "Trump Administration",
  "Labor Rights": "Federal Employees",
  "Legal Challenges": "Legal Challenges",
  "Legal Issues": "Legal Challenges",
  "Legal Proceedings": "Legal Challenges",
  "Loan Maturity": "Banking Relationships",
  "Loan Rejection": "Loan Rejections",
  "Loan Rejections": "Financial Markets",
  "Lobbying": "Campaign Finance",
  "MAGA Inc.": "Campaign Finance",
  "Mar-a-Lago": "Trump Organization",
  "Market Crash": "Financial Markets",
  "Mass deportations": "Deportations",
  "Media Capture": "Press Freedom",
  "Medicaid": "Regulatory Rollback",
  "Melania Trump": "Crypto",
  "Memecoins": "Crypto",
  "Meta": "Tech Platforms",
  "Middle East Investments": "Foreign Influence",
  "Military veterans": "Citizens detained",
  "Misinformation": "Free Speech",
  "Monetization of Office": "Conflicts of Interest",
  "Musk Companies": "Musk Companies",
  "National Park Service": "Federal Agencies",
  "National Security": "National Security",
  "National Service": "Federal Agencies",
  "New York City": "New York",
  "NSA": "National Security",
  "NTSB": "Federal Agencies",
  "Office of Government Ethics": "Ethics",
  "Ongoing": null,
  "Oversight": "Oversight Interference",
  "Oversight Interference": "Oversight Interference",
  "Pam Bondi": "Department of Justice",
  "Pardon": "Influence Peddling",
  "pattern": "Ongoing",
  "Pay to Play": "Pay-to-Play",
  "Payment Services": "Financial Markets",
  "Peter Thiel": "Tech Platforms",
  "Personal Enrichment": "Conflicts of Interest",
  "Pete Hegseth": "Trump Administration",
  "Platform Moderation": "Tech Platforms",
  "Political Donation": "Influence Peddling",
  "Political Fallout": "Influence Peddling",
  "Political Merchandise": "MAGA Inc.",
  "Press Freedom": "Press Freedom",
  "Private access": "Pay-to-Play",
  "Professional Bank": "Banking Relationships",
  "Public Protests": "Free Speech",
  "Public Safety": "Public Safety",
  "Qatar": "Foreign Influence",
  "Racial profiling": "Immigration Actions",
  "Rare Earths": "Foreign Influence",
  "Real Estate": "Financial Markets",
  "Refinancing Risk": "Financial Markets",
  "Regulatory Capture": "Regulatory Rollback",
  "Regulatory Rollback": "Regulatory Rollback",
  "Retaliation": "Oversight Interference",
  "Rights Violations": "Rights Violations",
  "Russia": "Foreign Influence",
  "Saudi Arabia": "Foreign Influence",
  "Schedule F": "Federal Employees",
  "SEC Investigations": "Legal Challenges",
  "Senate": "Legal Challenges",
  "Silicon Valley": "Tech Platforms",
  "Smithsonian": "Federal Agencies",
  "Social Media": "Tech Platforms",
  "SpaceX": "Musk Companies",
  "Starlink": "Musk Companies",
  "State Department": "Federal Agencies",
  "Stablecoins": "Crypto",
  "Structural Conflicts": "Conflicts of Interest",
  "Supreme Court": "Legal Challenges",
  "Tariffs": "Tariffs",
  "Tax": "Legal Challenges",
  "Tax Reform": "Legal Challenges",
  "Tech": "Tech Platforms",
  "Tech Billionaires": "Conflicts of Interest",
  "Tech Platforms": "Tech Platforms",
  "Tesla": "Musk Companies",
  "Tether": "Crypto",
  "The Boring Company": "Musk Companies",
  "Trade": "Financial Markets",
  "Trade Policy": "Tariffs",
  "Transparency": "Transparency",
  "Treasury Department": "Federal Agencies",
  "Trump": "Donald Trump",
  "Trump Administration": "Trump Administration",
  "Trump Business": "Trump Organization",
  "Trump Hotels": "Trump Organization",
  "Trump International Hotel": "Trump Organization",
  "Trump National Doral": "Trump Organization",
  "Trump Organization": "Trump Organization",
  "Trump Tower": "Trump Organization",
  "Turkey": "Foreign Influence",
  "Ukraine": "Foreign Influence",
  "Unions": "Federal Employees",
  "USD1": "Crypto",
  "US Citizens Detained": "Citizens detained",
  "US citizens detained": "Citizens detained",
  "USIP": "Federal Agencies",
  "Verizon": "Tech Platforms",
  "Veterans Affairs": "Federal Agencies",
  "Visas revoked": "Immigration Actions",
  "Vote Buying": "Quid Pro Quo Corruption",
  "Warrantless raids": "Due Process Violations",
  "Watchdog Removal": "Oversight Interference",
  "Whistleblower Retaliation": "Oversight Interference",
  "White House": "Trump Organization",
  "White House Access": "Campaign Finance",
  "World Economic Forum": "World Economic Forum",
  "World Liberty Financial": "Crypto",
  "AI Policy": "AI Surveillance",
  "Arts and Culture": "Press Freedom",
  "Copyright Law": "Legal Challenges",
  "xAI": "Musk Companies",
  "Nayib Bukele": "El Salvador",
  "Patrick McHenry": "Trump Administration",
  "Russell Vought": "Trump Administration",
  "Howard Lutnick": "Treasury Department",
  "Brandon Lutnick": "Trump Organization",
  "Donald Trump Jr.": "Trump Organization",
  "Cryptocurrency": "Crypto",
  "Congressional Action": "Oversight Interference",
  "Project 2025": "Trump Administration",
  "Housing Policy": "Federal Agencies",
  "Military Deployment": "Military Deployment",
  "Department of Justice": "Federal Agencies",
  "NASA": "Federal Agencies",
  "SEC": "Federal Agencies",
  "Supreme Court": "Legal Challenges",
  "Lobbying": "Campaign Finance",
  "Housing Policy": "Federal Agencies",
  "Labor Organizing": "Federal Employees",
  "Foreign Policy": "Foreign Influence",
  "Whistleblowers": "Oversight Interference",
  "Procurement": "Federal Agencies",
  "Monetization of Presidency": "Monetization of Presidency",
  "Quid Pro Quo Corruption": "Quid Pro Quo Corruption",
  "Department of Justice": "Federal Agencies",
  "Truth Social": "Trump Organization",
  
  // Consolidations from 8-30-25 audit
  "Bureau of Labor Statistics": "Federal Agencies",
  "General Services Administration": "Federal Agencies", 
  "National Science Foundation": "Federal Agencies",
  "FBI": "Federal Agencies",
  "Federal Reserve": "Federal Agencies",
  "FEMA": "Federal Agencies",
  "USAID": "Federal Agencies",
  "Deportations": "Detention Archipelago",
  "Deportation Archipelago": "Detention Archipelago",
  "DHS": "Department of Homeland Security",
  "JD Vance": "Trump Administration",
  "Robert F. Kennedy Jr.": "Trump Administration",
  "Economic Policy": "Financial Markets",
  "Visa Policy": "Immigration Actions", 
  "Public Health": "Department of Health and Human Services",
  "International Trade": "Financial Markets",
  "Judicial Review": "Legal Challenges",
  "Private Prisons": "Detention Archipelago",
  "Fox News": "Press Freedom",
  "Civil-Military Relations": "National Security",
  "Military Deployment": "Posse Comitatus",
  "Federal Takeover of Local Authority": "Posse Comitatus",
  "Smithsonian Institution": "Federal Agencies", 
  "Department of Health and Human Services": "Federal Agencies",
  "Department of State": "Federal Agencies",
  "Smithsonian Institution": "Federal Agencies",

// October 2025 consolidation round

// Federal Agencies - rare tags
"Bureau of Prisons": "Federal Agencies",
"Centers for Disease Control and Prevention": "Federal Agencies",
"Department of Agriculture": "Federal Agencies",
"Department of Commerce": "Federal Agencies",
"Department of Education": "Federal Agencies",
"Department of Energy": "Federal Agencies",
"Department of Housing and Urban Development": "Federal Agencies",
"Department of the Interior": "Federal Agencies",
"Department of Labor": "Federal Agencies",
"Department of Transportation": "Federal Agencies",
"Department of Veterans Affairs": "Federal Agencies",
"Environmental Protection Agency": "Federal Agencies",
"Office of Management and Budget": "Federal Agencies",
"Small Business Administration": "Federal Agencies",
"U.S. Citizenship and Immigration Services": "Federal Agencies",
"USCIS": "Federal Agencies",
"ATF": "Federal Agencies",
"DEA": "Federal Agencies",
"U.S. Marshals Service": "Federal Agencies",

// Tech Platforms - rare companies
"Amazon": "Tech Platforms",
"Google": "Tech Platforms",
"Microsoft": "Tech Platforms",
"OpenAI": "Tech Platforms",
"TikTok": "Tech Platforms",

// Foreign Influence - geographic consolidation
"Afghanistan": "Foreign Influence",
"Canada": "Foreign Influence",
"Colombia": "Foreign Influence",
"Cuba": "Foreign Influence",
"Gaza": "Foreign Influence",
"Guatemala": "Foreign Influence",
"Haiti": "Foreign Influence",
"Honduras": "Foreign Influence",
"India": "Foreign Influence",
"Iran": "Foreign Influence",
"Iraq": "Foreign Influence",
"Israel": "Foreign Influence",
"Mexico": "Foreign Influence",
"Nicaragua": "Foreign Influence",
"North Korea": "Foreign Influence",
"Pakistan": "Foreign Influence",
"Panama": "Foreign Influence",
"Russia": "Foreign Influence",
"Syria": "Foreign Influence",
"Turkey": "Foreign Influence",
"Ukraine": "Foreign Influence",
"United Arab Emirates": "Foreign Influence",
"Venezuela": "Foreign Influence",
"Yemen": "Foreign Influence",

// Immigration Actions - related terms
"Border Security": "Immigration Actions",
"Citizenship": "Immigration Actions",
"Refugee Policy": "Immigration Actions",

// Banking Relationships - rare institutions
"Deutsche Bank": "Banking Relationships",
"JPMorgan Chase": "Banking Relationships",
"Wells Fargo": "Banking Relationships",

// Trump Organization - family members
"Ivanka Trump": "Trump Organization",
"Lara Trump": "Trump Organization",

// October 2025 - Round 2: Acronyms, variants, and remaining rare tags

// Acronyms and variant spellings
"CDC": "Federal Agencies",
"Federal Bureau of Investigation": "Federal Agencies",
"Homeland Security Department": "Federal Agencies",

// Replace the "Political figures (all 1 entry each)" section in tagMap.js with this:

// Political figures - all single entries, retired
"Hunter Biden": null,
"James Biden": null,
"Ilhan Omar": null,
"James Comey": null,
"John Bolton": null,
"Kash Patel": null,
"Lindsey Halligan": null,
"Lisa Cook": null,
"Lisa Monaco": null,
"Marco Rubio": null,

// Business entities
"ByteDance": "Tech Platforms",
"CEFC China Energy": "Foreign Influence",
"Fox Corporation": "Press Freedom",
"MGX": "Foreign Influence",
"Oracle": "Tech Platforms",

// Specific violations and concepts
"Civil Rights": "Rights Violations",
"Congressional Ethics": "Ethics",
"Constitutional Crisis": "Legal Challenges",
"Corporate Retaliation": "Oversight Interference",
"Executive Power": "Legal Challenges",
"Federal Courts": "Legal Challenges",
"Financial Disclosure": "Transparency",
"Financial Misconduct": "Financial Markets",
"Financial Oversight Collapse": "Oversight Interference",
"Freedom of Information Act": "Transparency",
"Government Shutdown": "Trump Administration",
"Law Enforcement Retaliation": "Oversight Interference",
"Military Alliances": "National Security",
"National Institutes of Health": "Federal Agencies",
"Obstruction of Justice": "Legal Challenges",
"Political Corruption": "Quid Pro Quo Corruption",
"Redistricting": "Legal Challenges",
"Religious Nationalism": "Christian Nationalism",
"Scientific Retaliation": "Oversight Interference",
"U.S. Coast Guard": "Federal Agencies",
"Venture Capital": "Financial Markets",
"Whistleblower Protections": "Oversight Interference",
"Workforce Purge": "Federal Employees",

// Geographic tags (keeping minimal for now)
"Chicago": null,
"Texas": null,

// Tags to keep separate (explicitly noting for documentation)
// DOJ Capture (10 entries) - keeping separate
// Fed Capture (5 entries) - keeping separate  
// National Guard (7 entries) - keeping separate
// Christian Nationalism (5 entries) - keeping separate

// ========================================
// November 2025 Consolidation Round
// ========================================

// Merge similar/overlapping tags
"Trade and Tariffs": "Tariffs",
"Trump Family Enterprises": "Trump Organization",
"Corporate Influence": "Conflicts of Interest",
"ICE Deployments": "Immigration Actions",
"Voting Rights": "Rights Violations",

// Agency-specific tags → Federal Agencies (too granular for current scale)
"Cybersecurity and Infrastructure Security Agency": "Federal Agencies",
"Department of the Treasury": "Federal Agencies",
"Government Accountability Office": "Federal Agencies",

// Strategic preservation (explicitly documented)
// "Authoritarian Consolidation" - KEEP SEPARATE (likely to grow)
// "China Relations" - KEEP SEPARATE (warrants distinct tracking)
// "Martial Law Threats" - KEEP SEPARATE (extreme severity marker)
// "Trump Family v. U.S. Interests" - KEEP SEPARATE (monitoring until 8-10 examples)
};