// scripts/tagMap.js
module.exports = {
  // Existing mappings
  "pay-to-play": "Pay-to-Play",
  "Donor Access": "Pay-to-Play",
  "elite access": "Pay-to-Play",
  "private access": "Pay-to-Play",
  "Abuse of Power": "Abuse of Office",
  "Monetization of Office": "Self-Dealing",
  "Family Enrichment": "Self-Dealing",
  "Cryptocurrency": "Crypto",
  "Bitcoin": "Crypto",
  "$TRUMP Coin": "Crypto",
  "Stablecoin": "Crypto",
  "DeFi": "Crypto",
  "Crypto Ball": "Crypto",
  "Truth.Fi": "World Liberty Financial",
  "Trump Media": "Trump Organization",
  "Truth Social": "Trump Organization",
  "Trump": "Donald Trump",
  "Eric Trump": "Trump Family",
  "Deutsche Bank": "Banking Relationships",
  "Wells Fargo": "Banking Relationships",
  "Goldman Sachs": "Banking Relationships", 
  "Bank of America": "Banking Relationships",
  "JPMorgan Chase": "Banking Relationships",
  "Professional Bank": "Banking Relationships",
  "Capital One": "Banking Relationships",
  "Signature Bank": "Banking Relationships",
  "PayPal": "Payment Services",
  "Stripe": "Payment Services",
  "Square": "Payment Services",
  "January 6": "Capitol Riot Fallout",
  "Capitol Riot": "Capitol Riot Fallout",
  "Trump Campaign": "Capitol Riot Fallout",
  "Campaign Finance Violations": "Campaign Finance",
  "Campaign Fundraising": "Fundraising",
  "fundraising": "Fundraising",
  "dark money": "Campaign Finance",
  "SuperPACs": "Campaign Finance",
  "Watchdog Removal": "Oversight Interference",
  "Inspectors General": "Oversight Interference",
  "Oversight": "Oversight Interference",
  "Market Crash": "Financial Markets",
  "Refinancing Risk": "Financial Markets",
  "Reputational Risk": "Financial Markets",
  "Finance": "Financial Markets",
  "Financial Institutions": "Financial Markets",
  "Pardon": "Influence Peddling",
  "Political Donation": "Influence Peddling",
  "Political Fallout": "Influence Peddling",
  "Tech Regulation": "Tech Platforms",
  "Facebook": "Tech Platforms",
  "Meta": "Tech Platforms",
  "Mar-a-Lago": "Trump Residences",
  "White House": "Trump Residences",
  "SpaceX": "Musk Companies",
  "Tesla": "Musk Companies",
  "Account Terminations": "Account Closures",
  "Loan Rejection": "Loan Rejections",
  "ethics": "Ethics",

  // Consolidations from this pass
  "Trump Family": "Trump Organization",
  "Trump Residences": "Trump Organization",
  "Cruel and unusual punishment": "Rights Violations",
  "Excessive force": "Rights Violations",
  "Warrantless raids": "Due Process Violations",
  "Mass deportations": "Deportations",
  "Wrongful deportation": "Deportations",

  "Economic Policy": "Financial Markets",
  "Self-Dealing": "Conflicts of Interest",
  "Personal Enrichment": "Conflicts of Interest",
  "Conflict of Interest": "Conflicts of Interest",
  "Pay-to-Play": "Campaign Finance",
  "Fundraising": "Campaign Finance",
  "Bond Market": "Financial Markets",

  "Crypto Regulation": "Crypto",
  "Memecoins": "Crypto",
  "Blockchain": "Crypto",
  "Digital Assets": "Crypto",
  "Digital Asset Policy": "Crypto",
  "Fintech": "Financial Markets",
  "USD1": "Crypto",
  "Solana": "Crypto",
  "Strategic Reserve": "Crypto",

  "Regulatory Capture": "Regulatory Rollback",
  "Regulatory Evasion": "Regulatory Rollback",

  "X Platform": "Musk Companies",

  "Abuse of Office": "Oversight Interference",
  "Falsification of Records": "Oversight Interference",
  "Corporate Accountability": "Oversight Interference",
  "Office of Government Ethics": "Ethics",
  "Terms of Service Violations": "Tech Platforms",
  "Platform Moderation": "Tech Platforms",
  "Deplatforming": "Tech Platforms",
  "Settlement": "Legal Challenges",
  "legal challenges": "Legal Challenges",
  "Legal challenges": "Legal Challenges",
  "Investor Protection": "Financial Markets",
  "Alternative Finance": "Financial Markets",
  "Account Closures": "Banking Relationships",
  "Loan Maturity": "Banking Relationships",
  "Brokerage Termination": "Banking Relationships",
  "Debanking": "Banking Relationships",
  "Insurance": "Financial Markets",
  "Real Estate": "Financial Markets",
  "Spectrum Interference": "Satellite Communications",
  "Surveillance": "Data Privacy",
  "Middle East Investments": "Foreign Influence",
  "Corporate Enforcement": "Ethics",
  "Anti-Corruption": "Ethics",
  "Misinformation": "Free Speech",
  "Free speech": "Free Speech",
  "Contracts Termination": "Business Relationships",
  "New York City": "New York",
  "unofficial event": "Campaign Event",
  "early administration": "Trump Administration",
  "pattern": "Ongoing",
  "STABLE Act": "Crypto",
  "Donor Enrichment": "Conflicts of Interest",
  "Resource Extraction": "Conflicts of Interest",
  "Election Interference": "Vote Buying",
  "Political Merchandise": "Merchandising",
  "Religion and Politics": "Merchandising",
  "Merchandising": "MAGA Inc.",
  "Bible Sales": "MAGA Inc.",
  "Trade Policy": "Tariffs",
  "Global Economy": "Financial Markets",
  "Payment Services": "Financial Markets",
  "World Economic Forum": "World Economic Forum",

  // New cleanups/consolidations
  "US Citizens Detained": "Citizens detained",
  "SSA": "Social Security Administration",
  "Department of Government Efficiency": "DOGE",
  "Federal Workforce": "Federal Employees",
  "Censorship": "Press Freedom",
  "Signal Scandal": "Oversight Interference",
  
  // Government Agency Consolidations
  "DHS": "Department of Homeland Security",
  "DOJ": "Department of Justice",
  "NSA": "National Security",
  "CISA": "Cybersecurity",
  "USCIS": "Department of Homeland Security",
  
  // Financial Sector Consolidations
  "Aon": "Financial Markets",
  "Fidelity Investments": "Financial Markets",
  "Binance": "Crypto",
  "Cushman & Wakefield": "Business Relationships",
  
  // Immigration Tags
  "Citizens arrested": "Citizens detained",
  "Long-term residents": "Immigration Actions",
  "Denaturalization": "Immigration Actions",
  
  // Musk Company Tags
  "Verizon": "Tech Platforms",
  "Apple": "Tech Platforms",
  
  // Family and Personnel Consolidations
  // "Jared Kushner": "Trump Organization", // Keeping separate per feedback
  "Changpeng Zhao": "Crypto",
  "Laura Loomer": "Trump Administration",
  "Scott Bessent": "Treasury Department",
  "Pam Bondi": "Department of Justice",
  "Peter Thiel": "Tech Platforms",
  
  // Rare Location Tags
  "El Salvador": "Deportations",
  "Canada": "Tariffs",
  "Greenland": "Foreign Influence",
  
  // DOGE-Related Consolidations
  "Workforce Reductions": "DOGE",
  "Government Restructuring": "DOGE",
  "Government Administration": "Oversight Interference",

  // Additional consolidations based on entry review
  "Asylum seekers": "Immigration Actions",
  "Border crossing": "Immigration Actions",
  "International students": "Immigration Actions",
  "Student Visas": "Immigration Actions",
  "Visas revoked": "Immigration Actions",
  "US citizens detained": "Citizens detained",
  "Detentions": "Citizens detained", 
  "Children detained": "Family separation",

  "FAA": "Federal Agencies",
  "FCC": "Federal Agencies",
  "FTC": "Federal Agencies",
  "Federal Oversight": "Oversight Interference",
  "Government Accountability": "Oversight Interference",
  "Government Oversight": "Oversight Interference",
  "Intelligence Community": "National Security",
  "Cabinet Reshuffling": "Trump Administration",

  "Legal Issues": "Legal Challenges",
  "Legal Proceedings": "Legal Challenges",

  "International academics": "Academic Freedom",

  "Foreign Aid": "Foreign Influence",
  "Foreign Policy": "Foreign Influence",

  "Housing": "Social Security Administration",
  "Healthcare impacts": "Regulatory Rollback",
  "Community response": "Press Freedom",

  // New additional consolidations to fix remaining issues
  "Military veterans": "Citizens detained",
  "Healthcare": "Regulatory Rollback",
  "Immigration Policy": "Immigration Actions",
  "Immigration": "Immigration Actions", // Added this line to consolidate Immigration with Immigration Actions

  // Map to null to filter out this tag
  "California": null,
  "Egypt": null,
  "Florida": null,
  "Guatemala": null,
  "Illinois": null,
  "India": null,
  "Japan": null,
  "Maryland": null,
  "Massachusetts": null,
  "Mexico": null,
  "New Jersey": null,
  "New York": null,
  "Texas": null,
  "Turkey": null,
  "Venezuela": null,
  "Vermont": null,
  "Virginia": null,
  "Wisconsin": null,

  // Unchanged from previous
  "US": null,
  "Ongoing": null,
  "2025": null
};