// scripts/tagMap.js — fully updated based on audit consolidation plan
module.exports = {
  // Original mappings + preserved historical tags
  "pay-to-play": "Pay-to-Play",
  "Donor Access": "Pay-to-Play",
  "elite access": "Pay-to-Play",
  "private access": "Pay-to-Play",
  "Abuse of Power": "Oversight Interference",
  "Monetization of Office": "Conflicts of Interest",
  "Family Enrichment": "Conflicts of Interest",
  "Cryptocurrency": "Crypto",
  "Bitcoin": "Crypto",
  "$TRUMP Coin": "Crypto",
  "Melania Trump": "Crypto",
  "Stablecoin": "Crypto",
  "DeFi": "Crypto",
  "Crypto Ball": "Crypto",
  "Truth.Fi": "World Liberty Financial",
  "Trump Media": "Trump Organization",
  "Truth Social": "Trump Organization",
  "Trump": "Donald Trump",
  "Eric Trump": "Trump Organization",
  "CIC Ventures LLC": "Trump Organization",
  "Deutsche Bank": "Banking Relationships",
  "Wells Fargo": "Banking Relationships",
  "Goldman Sachs": "Banking Relationships",
  "Bank of America": "Banking Relationships",
  "JPMorgan Chase": "Banking Relationships",
  "Professional Bank": "Banking Relationships",
  "Capital One": "Banking Relationships",
  "Signature Bank": "Banking Relationships",
  "PayPal": "Financial Markets",
  "Stripe": "Financial Markets",
  "Square": "Financial Markets",
  "January 6": "Capitol Riot Fallout",
  "Capitol Riot": "Capitol Riot Fallout",
  "Trump Campaign": "Capitol Riot Fallout",
  "Campaign Finance Violations": "Campaign Finance",
  "Campaign Fundraising": "Campaign Finance",
  "fundraising": "Campaign Finance",
  "dark money": "Campaign Finance",
  "SuperPACs": "Campaign Finance",
  "Watchdog Removal": "Oversight Interference",
  "Inspectors General": "Oversight Interference",
  "Oversight": "Oversight Interference",
  "Market Crash": "Financial Markets",
  "Refinancing Risk": "Financial Markets",
  "Reputational Risk": "Financial Markets",
  "Finance": "Financial Markets",
  "Financial Institutions": "Financial Markets",
  "Pardon": "Influence Peddling",
  "Political Donation": "Influence Peddling",
  "Political Fallout": "Influence Peddling",
  "Tech Regulation": "Tech Platforms",
  "Facebook": "Tech Platforms",
  "Meta": "Tech Platforms",
  "Mar-a-Lago": "Trump Organization",
  "White House": "Trump Organization",
  "SpaceX": "Musk Companies",
  "Tesla": "Musk Companies",
  "Account Terminations": "Banking Relationships",
  "Loan Rejection": "Loan Rejections",
  "ethics": "Ethics",

  // Consolidation-aware entries
  "Trump Family": "Trump Organization",
  "Trump Residences": "Trump Organization",
  "Cruel and unusual punishment": "Rights Violations",
  "Excessive force": "Rights Violations",
  "Warrantless raids": "Due Process Violations",
  "Mass deportations": "Deportations",
  "Wrongful deportation": "Deportations",
  "Self-Dealing": "Conflicts of Interest",
  "Personal Enrichment": "Conflicts of Interest",
  "Conflict of Interest": "Conflicts of Interest",
  "Bond Market": "Financial Markets",
  "Crypto Regulation": "Crypto",
  "Memecoins": "Crypto",
  "Blockchain": "Crypto",
  "Digital Assets": "Crypto",
  "Digital Asset Policy": "Crypto",
  "Fintech": "Financial Markets",
  "USD1": "Crypto",
  "Solana": "Crypto",
  "Strategic Reserve": "Crypto",
  "Regulatory Capture": "Regulatory Rollback",
  "Regulatory Evasion": "Regulatory Rollback",
  "X Platform": "Musk Companies",
  "Falsification of Records": "Oversight Interference",
  "Corporate Accountability": "Oversight Interference",
  "Office of Government Ethics": "Ethics",
  "Terms of Service Violations": "Tech Platforms",
  "Platform Moderation": "Tech Platforms",
  "Deplatforming": "Tech Platforms",
  "Settlement": "Legal Challenges",
  "legal challenges": "Legal Challenges",
  "Legal challenges": "Legal Challenges",
  "Investor Protection": "Financial Markets",
  "Alternative Finance": "Financial Markets",
  "Loan Maturity": "Banking Relationships",
  "Brokerage Termination": "Banking Relationships",
  "Debanking": "Banking Relationships",
  "Insurance": "Financial Markets",
  "Real Estate": "Financial Markets",
  "Spectrum Interference": "Satellite Communications",
  "Surveillance": "Data Privacy",
  "Signal Scandal": "Data Privacy",
  "Government Communications": "Data Privacy",
  "Middle East Investments": "Foreign Influence",
  "Corporate Enforcement": "Ethics",
  "Anti-Corruption": "Ethics",
  "Misinformation": "Free Speech",
  "Free speech": "Free Speech",
  "Contracts Termination": "Business Relationships",
  "New York City": "New York",
  "unofficial event": "Campaign Event",
  "early administration": "Trump Administration",
  "pattern": "Ongoing",
  "STABLE Act": "Crypto",
  "Donor Enrichment": "Conflicts of Interest",
  "Resource Extraction": "Conflicts of Interest",
  "Election Interference": "Vote Buying",
  "Political Merchandise": "MAGA Inc.",
  "Religion and Politics": "MAGA Inc.",
  "Merchandising": "MAGA Inc.",
  "Bible Sales": "MAGA Inc.",
  "Trade Policy": "Tariffs",
  "Global Economy": "Financial Markets",
  "Payment Services": "Financial Markets",
  "World Economic Forum": "World Economic Forum",
  "Foreign Business": "Foreign Influence",
  "Foreign Policy": "Foreign Influence",
  "Qatar": "Foreign Influence",
  "Saudi Arabia": "Foreign Influence",
  "Emoluments Clause": "Emoluments",
  "Pete Hegseth": "Trump Administration",
  "Media Capture": "Press Freedom",
  "Symbolic Actions": "Trump Administration",
  "FOIA": "Legal Challenges",
  "Regulatory Policy": "Regulatory Rollback",
  "Treasury": "Treasury Department",
  "Federal Bureau of Prisons": "Department of Justice",

  // Immigration and civil liberties
  "US Citizens Detained": "Citizens detained",
  "SSA": "Social Security Administration",
  "Department of Government Efficiency": "DOGE",
  "Federal Workforce": "Federal Employees",
  "Censorship": "Press Freedom",

  // Agency aliases
  "DHS": "Department of Homeland Security",
  "DOJ": "Department of Justice",
  "NSA": "National Security",
  "CISA": "Cybersecurity",
  "USCIS": "Department of Homeland Security",

  // Financial actors
  "Aon": "Financial Markets",
  "Fidelity Investments": "Financial Markets",
  "Binance": "Crypto",
  "Cushman & Wakefield": "Business Relationships",

  // Personnel & foreign affairs
  "Verizon": "Tech Platforms",
  "Apple": "Tech Platforms",
  "Changpeng Zhao": "Crypto",
  "Laura Loomer": "Trump Administration",
  "Scott Bessent": "Treasury Department",
  "Pam Bondi": "Department of Justice",
  "Peter Thiel": "Tech Platforms",

  // Locations
  "El Salvador": "Deportations",
  "Canada": "Tariffs",
  "Greenland": "Foreign Influence",

  // DOGE internal structure
  "Workforce Reductions": "DOGE",
  "Government Restructuring": "DOGE",
  "Government Administration": "Oversight Interference",

  // Civil rights and education
  "Asylum seekers": "Immigration Actions",
  "Border crossing": "Immigration Actions",
  "International students": "Immigration Actions",
  "Student Visas": "Immigration Actions",
  "Visas revoked": "Immigration Actions",
  "US citizens detained": "Citizens detained",
  "Detentions": "Citizens detained",
  "Children detained": "Family separation",
  "FAA": "Federal Agencies",
  "FCC": "Federal Agencies",
  "FTC": "Federal Agencies",
  "Federal Oversight": "Oversight Interference",
  "Government Accountability": "Oversight Interference",
  "Government Oversight": "Oversight Interference",
  "Intelligence Community": "National Security",
  "Cabinet Reshuffling": "Trump Administration",
  "Legal Issues": "Legal Challenges",
  "Legal Proceedings": "Legal Challenges",
  "International academics": "Academic Freedom",
  "Foreign Aid": "Foreign Influence",
  "Housing": "Social Security Administration",
  "Healthcare impacts": "Regulatory Rollback",
  "Community response": "Press Freedom",
  "Military veterans": "Citizens detained",
  "Healthcare": "Regulatory Rollback",
  "Immigration Policy": "Immigration Actions",
  "Immigration": "Immigration Actions",

  // Geographic filters
  "California": null,
  "Egypt": null,
  "Florida": null,
  "Guatemala": null,
  "Illinois": null,
  "India": null,
  "Japan": null,
  "Maryland": null,
  "Massachusetts": null,
  "Mexico": null,
  "New Jersey": null,
  "New York": null,
  "Texas": null,
  "Turkey": null,
  "Venezuela": null,
  "Vermont": null,
  "Virginia": null,
  "Wisconsin": null,
  "US": null,
  "Ongoing": null,
  "2025": null,
 // scripts/tagMap.js — complete, final, and fully implemented based on all audit recommendations
// Consolidations for rare and legacy tags (alphabetized)
  "Academic Freedom": "Academic Freedom",
  "Affinity Partners": "Trump Organization",
  "AI Surveillance": "AI Surveillance",
  "Alien Enemies Act": "Deportations",
  "AmeriCorps": "Federal Agencies",
  "Banking Relationships": "Financial Markets",
  "Business Relationships": "Trump Organization",
  "Business owners": "Trump Organization",
  "Campaign Event": "Campaign Finance",
  "Capitol Riot Fallout": "Capitol Riot Fallout",
  "CFPB": "Federal Agencies",
  "China": "Foreign Influence",
  "CIC Ventures LLC": "Trump Organization",
  "Citizens detained": "Immigration Actions",
  "Conflicts of Interest": "Conflicts of Interest",
  "Criminal Justice": "Oversight Interference",
  "Crypto": "Crypto",
  "Cybersecurity": "Data Privacy",
  "Data Breach": "Data Privacy",
  "Data Privacy": "Data Privacy",
  "Department of Defense": "Federal Agencies",
  "Department of Homeland Security": "Federal Agencies",
  "Department of Justice": "Federal Agencies",
  "Deportations": "Deportations",
  "DOGE": "DOGE",
  "Dollar Dominance": "Financial Markets",
  "Donald Trump": "Donald Trump",
  "Due Process Violations": "Rights Violations",
  "Elon Musk": "Elon Musk",
  "Emoluments Clause": "Emoluments",
  "Emoluments": "Legal Challenges",
  "Environmental Violations": "Regulatory Rollback",
  "Ethics": "Ethics",
  "Executive Order": "Legal Challenges",
  "Facial Recognition": "AI Surveillance",
  "Family separation": "Immigration Actions",
  "FCPA": "Legal Challenges",
  "Federal Agencies": "Federal Agencies",
  "Federal Budget": "Federal Agencies",
  "Federal Bureau of Prisons": "Department of Justice",
  "Federal Employees": "Federal Employees",
  "Financial Challenges": "Financial Markets",
  "Financial Disclosures": "Legal Challenges",
  "Financial Markets": "Financial Markets",
  "Foreign Business": "Foreign Influence",
  "Foreign Influence": "Foreign Influence",
  "Free Speech": "Free Speech",
  "GENIUS Act": "Legal Challenges",
  "Golden Dome": "National Security",
  "Government Communications": "Data Privacy",
  "Harvard University": "Academic Freedom",
  "ICE": "Federal Agencies",
  "Immigration Actions": "Immigration Actions",
  "Impeachment": "Legal Challenges",
  "Influence Peddling": "Campaign Finance",
  "Insider Trading": "Financial Markets",
  "IRS": "Federal Agencies",
  "Jared Kushner": "Trump Organization",
  "Kristi Noem": "Trump Administration",
  "Labor Rights": "Federal Employees",
  "Lee Greenwood": null,
  "Legal Challenges": "Legal Challenges",
  "Loan Rejections": "Financial Markets",
  "MAGA Inc.": "Campaign Finance",
  "Marjorie Taylor Greene": null,
  "Media Capture": "Press Freedom",
  "Melania Trump": "Crypto",
  "Musk Companies": "Musk Companies",
  "National Park Service": "Federal Agencies",
  "National Security": "National Security",
  "National Service": "Federal Agencies",
  "NTSB": "Federal Agencies",
  "Oversight Interference": "Oversight Interference",
  "Palantir": "Tech Platforms",
  "Press Freedom": "Press Freedom",
  "Public Safety": "Public Safety",
  "Qatar": "Foreign Influence",
  "Racial profiling": "Immigration Actions",
  "Rare Earths": "Foreign Influence",
  "Regulatory Rollback": "Regulatory Rollback",
  "Rights Violations": "Rights Violations",
  "Satellite Communications": "Musk Companies",
  "Saudi Arabia": "Foreign Influence",
  "SEC": "Federal Agencies",
  "Senate": "Legal Challenges",
  "Social Security Administration": "Federal Agencies",
  "State Department": "Federal Agencies",
  "Supreme Court": "Legal Challenges",
  "Tariffs": "Foreign Influence",
  "Tax Policy": "Financial Markets",
  "Tech Platforms": "Tech Platforms",
  "Transportation Department": "Federal Agencies",
  "Treasury Department": "Federal Agencies",
  "Trump Administration": "Trump Administration",
  "Trump Organization": "Trump Organization",
  "Vote Buying": "Campaign Finance",
  "Whistleblower Retaliation": "Oversight Interference",
  "World Liberty Financial": "Crypto"
};


